language: objective-c
osx_image: xcode7.3
gemfile: Gemfile
install: bundle install
script: bundle exec rake test:ci
cache:
  - bundler
  - cocoapods
notifications:
  slack:
    secure: "gGc1XxX9hiLuD2HbClgDXxfILVZhp/8J0BCe8oSrinHV29I7N7EQQdlnHp8KL//XWjBqISuzjlBPbf4d2MfDgzTg5l5tfroa3I9AL7q4EAP4RNSAYmvAHa0+7hpdqXv2DrIpnIVPM0Bc7eldpKkcDUjPL7zgv0S15VxbrQ4rZ1s="
  email:
    secure: "IZnl1A0IXPlycNqA0Lq4dyCc5xKqXAVxIQu3zWs62MlhCThP+6Qtj1bH80FjxqCer1Sz6hZbhcc4ipZLfyabis1bJXcdMTACtC4twMyyLW47lxHgzURyccT9rjkcA3Sc2re3VVoaX4/fW0Uc8YRdfr2GqQKCVvPc3PjRhY7b168="
